spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: "10140019"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8085

jwt:
  secret: "s3cReT_jwT_KEY_1234567890!_abcDEF"
  expiration: 86400000 # 24 saat (ms cinsinden)
